### ISSUE TITLE
How to use this to monitor changes?

### ISSUE THREAD

**Issue by jordibruin** [pmanot/Battery#2]
I made a basic implementation but it does not trigger for updates. Am I overlooking something?

    struct ContentView: View {
    
    let battery = Battery()
    
    @State var percentage: String = ""
    
    @State var state: String = ""
    
    var body: some View {
        VStack {
            
            Text("\(percentage)")
                .font(.largeTitle)
            Text(state)
        }
        .padding()
        .onAppear {
            setupBatteryNotifications()
        }
    }
    
    func setupBatteryNotifications() {
        battery.$percentage.sink { percentage in
            print("Battery percentage: \(percentage)")
            self.percentage = self.percentage + "-\(percentage)-"
        }

        battery.$state.sink { state in
            print("Battery state: \(state)")
            self.state = state.rawValue
        }

        battery.$isLowPowerModeEnabled.sink { isEnabled in
            print("Low power mode enabled: \(isEnabled)")
        }
    }
   }`

**Comment by pmanot** [comment]
I think the issue stems from not storing the cancellables. Updated the docs to include it. 
Try this -

```
struct ContentView: View {
    let battery = Battery()
    @State var percentage: String = ""
    @State var state: String = ""
    @State private var cancellables: [AnyCancellable] = []
    
    init() {
        
    }
    
    var body: some View {
        VStack {
            Text("\(percentage)")
                 .font(.largeTitle)
            Text(state)
        }
        .onAppear {
            setupBatteryNotifications()
        }
    }
    
    func setupBatteryNotifications() {
        battery.$percentage.sink { percentage in
            print("Battery percentage: \(percentage)")
            self.percentage = self.percentage + "-\(percentage)-"
        }
        .store(in: &cancellables)
        
        battery.$state.sink { state in
            print("Battery state: \(state)")
            self.state = state.rawValue
        }
        .store(in: &cancellables)
        
        battery.$isLowPowerModeEnabled.sink { isEnabled in
            print("Low power mode enabled: \(isEnabled)")
        }
        .store(in: &cancellables)
    }
}

```

**Comment by pmanot** [comment]
Alternatively, you could also use a StateObject / inject an ObservedObject. 

```
struct ContentView: View {
    @StateObject var battery = Battery()
    
    var body: some View {
        VStack {
            Text(battery.state.rawValue)
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

**Comment by jordibruin** [comment]
Works great thanks!
